apiVersion: apps/v1
kind: Deployment
metadata:
  name: aka-iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
      - image: anilapato/iam:1.1.4
        name: aka-iam
        ports:
        - containerPort: 80
      imagePullSecrets:
       - name: reg-aka-cred
