apiVersion: v1
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: docker Registry
      api_url: https://index.docker.io
      prefix: index.docker.io
      ping: no
      credentials: pullsecret:argocd/reg-aka-cred
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: argocd
